[tool.poetry]

name = "elections"
version = "1.0"
description = "APIs for voter registration status and ballots in Michigan."

authors = ["Citizen Labs <info@citizenlabs.com>"]

[tool.poetry.dependencies]

python = "^3.7"

# Django
django = "~2.2.18"
django-grappelli = "^2.11"
django-filter = "^2.0"
django-model-utils = "^3.1"

# Django REST Framework
djangorestframework = "^3.8"
drf-yasg = "^1.9"
django-cors-headers = "^2.4"

# Databases
dj-database-url = "^0.5.0"
psycopg2-binary = "*"

# Caches
django-redis-cache = "*"

# Markdown
markdown = "*"
pymdown-extensions = "*"
pygments = "*"

# Utilities
beautifulsoup4 = "^4.6"
factory_boy = "*"
fake-useragent = "~0.1.11"
minilog = "^1.2.5"
nameparser = "^1.0.4"
pendulum = "*"
requests = "^2.19"
requests_cache = "*"

# Production Server
gunicorn = "^19.8"
whitenoise = "^4.1.4"
bugsnag = "^3.4"

[tool.poetry.dev-dependencies]

# Formatting
isort = "4.3.21"
black = "19.3b0"

# Linters
pylint = "^2.0"
pylint-django = "*"
mypy = "*"

# Testing
pytest = "^5.2.1"
pytest-django = "*"
pytest-describe = "*"
pytest-expecter = "^1.3"
pytest-vcr = "*"
pytest-cov = "*"
pytest-watch = "*"
ipdb = "~0.12.2"  # export PYTHONBREAKPOINT=ipdb.set_trace

# Utilities
django-extensions = "*"
pygraphviz = "*"

# Development Server
django-debug-toolbar = "*"
django-livereload-server = "*"

# Notebooks
jupyter = "^1.0.0"

[tool.black]

target_version = ['py37']
skip-string-normalization = true
